### ISSUE TITLE
Не билдится Dockerfile: падает на 16 шагу

### ISSUE THREAD

**Issue by strangeronline** [NikiforovAll/csharp_workshop#3]
Step 16/26 : COPY ./NuGet.config ${HOME}/nuget.config
COPY failed: stat /var/lib/docker/tmp/docker-builder998502568/NuGet.config: no such file or directory

**Comment by NikiforovAll** [comment]
Хочу попросить вас, предоставить сценарий, чтобы я мог попытаться воспроизвести его локально.

У меня билдится образм при запуске: 

`docker build . --no-cache -t csharp_workshop:tmp`

I recommend you to try:

```bash
cd .devcontainer
docker-compose up
```
