### ISSUE TITLE
Может стоит уже использовать в контейнере не релиз кандидат? И добавить установку  dotnet-script

### ISSUE THREAD

**Issue by strangeronline** [NikiforovAll/csharp_workshop#4]
$ dotnet tool install -g dotnet-script
You can invoke the tool using the following command: dotnet-script
Tool 'dotnet-script' (version '1.0.1') was successfully installed.

$ dotnet script
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.
  - The following frameworks were found:
      3.1.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
      5.0.0-rc.2.20475.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=ubuntu.20.04-x64

**Comment by NikiforovAll** [comment]
Я пытался поднять jupyter notebooks на .net5 и добавил следующие файлы.
```
  // Dockerfile
  58   │ RUN mkdir $HOME/dotnet_install && cd $HOME/dotnet_install
  59   │ RUN curl -H 'Cache-Control: no-cache' -L https://aka.ms/install-dotnet-preview -o install-dotnet-preview.sh
  60   │ RUN sudo bash install-dotnet-preview.sh
```
У меня не вышло, так как kernel направлен на .NET Core 3.1.

Изначально не планировал запускать в докере `samples/projects`, `samples/scripts`. Но буду рад PR. 

* Правки в Dockerfile 
* Инструкции по тому как запустить примеры из 'samples/*` внутри контейнера.

E.g.
```bash
❯ docker exec devcontainer_notebook_1 dotnet --list-sdks
3.1.301 [/usr/share/dotnet/sdk]
5.0.100-rc.1.20452.10 [/usr/share/dotnet/sdk]

 // we can use dotnet-script or dotnet run to show the demos without the necessity to attach to the container  
```

---

Кроме того, у меня есть упакованая рабочая среда как devcontainer отдельно, может вам будет интересно https://github.com/users/NikiforovAll/packages/container/package/devcontainers%2Fdotnet

**Comment by strangeronline** [comment]
Это максимум, что я добился
$ dotnet-script nullable-reference-types.csx
Unable to restore packages from '/home/jovyan/.cache/dotnet-script/home/jovyan/samples/scripts/netcoreapp3.1/script.csproj'. Make sure that all script files contains valid NuGet references
fail: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      Could not execute because the application was not found or a compatible .NET SDK is not installed.
fail: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      Possible reasons for this include:
fail: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
        * You intended to execute a .NET program:
fail: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
            The application 'restore' does not exist.
fail: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
        * You intended to execute a .NET SDK command:
fail: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
            A compatible installed .NET SDK for global.json version [5.0.100] from [/home/jovyan/samples/scripts/global.json] was not found.
fail: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
            Install the [5.0.100] .NET SDK or update [/home/jovyan/samples/scripts/global.json] with an installed .NET SDK:
$

Ну что-ж тратить время на запуск в контейнере не буду 
Спасибо за альтернативный контейнер.

**Comment by NikiforovAll** [comment]
Да, к сожалению из коробки это не работает, так как контейниризацию я сделал только для ноутбуков.
